// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqu8nZ5C1raWDOC2uIUL6LgXNIvNvNuzo',
    appId: '1:693114114201:web:dc72b4c1e35bb0f41ae808',
    messagingSenderId: '693114114201',
    projectId: 'boutiqueflutter-b5974',
    authDomain: 'boutiqueflutter-b5974.firebaseapp.com',
    storageBucket: 'boutiqueflutter-b5974.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcwQWIqK5zWmKtRx8QIRloJQRBn_OVr7g',
    appId: '1:693114114201:android:6fe2668bf48633a51ae808',
    messagingSenderId: '693114114201',
    projectId: 'boutiqueflutter-b5974',
    storageBucket: 'boutiqueflutter-b5974.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVG25s0NgTD6uQn0HBD4cCtuxyOQqIrBc',
    appId: '1:693114114201:ios:7c5a7898bb7c021b1ae808',
    messagingSenderId: '693114114201',
    projectId: 'boutiqueflutter-b5974',
    storageBucket: 'boutiqueflutter-b5974.firebasestorage.app',
    iosBundleId: 'com.example.boutiqueFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVG25s0NgTD6uQn0HBD4cCtuxyOQqIrBc',
    appId: '1:693114114201:ios:7c5a7898bb7c021b1ae808',
    messagingSenderId: '693114114201',
    projectId: 'boutiqueflutter-b5974',
    storageBucket: 'boutiqueflutter-b5974.firebasestorage.app',
    iosBundleId: 'com.example.boutiqueFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqu8nZ5C1raWDOC2uIUL6LgXNIvNvNuzo',
    appId: '1:693114114201:web:e5ceae52caf453ab1ae808',
    messagingSenderId: '693114114201',
    projectId: 'boutiqueflutter-b5974',
    authDomain: 'boutiqueflutter-b5974.firebaseapp.com',
    storageBucket: 'boutiqueflutter-b5974.firebasestorage.app',
  );
}
